---
version: "3.9"

services:
  statistics:
    container_name: statistics
    platform: linux/x86_64
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
    volumes:
      - ../src:/src
    ports:
      - "8050:8000"
    environment:
      - API_ENVIRONMENT=${API_ENVIRONMENT}
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    depends_on:
      - statistics-db
    networks:
      - innotter-statistics-network

  statistics-db:
    container_name: statistics-pg
    image: postgres:14.5
    volumes:
      - pgdata_statistics:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: statistics
      POSTGRES_PASSWORD: statistics
      POSTGRES_DB: statistics
    networks:
      - innotter-statistics-network

volumes:
  pgdata_statistics:

networks:
  innotter-statistics-network:
    external: true
