---
version: '3.8'

services:
  statistics-db:
    image: postgres:14.5
    container_name: statistics-pg
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: statistics
      POSTGRES_PASSWORD: statistics
      POSTGRES_DB: statistics
    volumes:
      - pgdata_statistics:/var/lib/postgresql/data

  statistics:
    platform: linux/x86_64
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
    container_name: statistics
    volumes:
      - ../src:/src
    ports:
      - "8050:8000"
    environment:
      - API_ENVIRONMENT=${API_ENVIRONMENT}
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - statistics-db

volumes:
  pgdata_statistics:
