name: Build & push docker image

on: [push, pull_request]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    name: Build & push docker image

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v22
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-multi-buildx

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ../
          file: docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/uladzislaubaranau/statistics-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
